# Default values for test-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: test-api
  tag: stable
  pullPolicy: IfNotPresent
  pullSecret: unknown

probes:
  enabled: false

appsettings:
  logging:
    logLevel: "Warning"
  TestApiDb:
    connectionString: ""
  messaging:
    kafka:
      producer:
        bootstrapServers: ""
      consumer:
        bootstrapServers: ""
  dependencies:
    invoices:
      baseUrl: ""

ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "$2"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host:
    name: unknown
    tlsSecretName: Your_Tls_Secret_Name
  path: /

containerPort: 443
servicePort: 8081

nodeSelector: {}

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - test-api
          topologyKey: kubernetes.io/hostname

tolerations: []